//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacon.DAL.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationLinkUserTypePermission
    {
        public int ApplicationLinkId { get; set; }
        public long UserTypeId { get; set; }
        public bool Disable { get; set; }
    
        public virtual ApplicationLink ApplicationLink { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
