//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacon.DAL.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationLink()
        {
            this.ApplicationLinkUserTypePermissions = new HashSet<ApplicationLinkUserTypePermission>();
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public int DisplayOrder { get; set; }
        public string LanguageResourceID { get; set; }
        public string GroupName { get; set; }
        public string LinkController { get; set; }
        public string LinkAction { get; set; }
        public bool Disable { get; set; }
    
        public virtual LanguageResource LanguageResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationLinkUserTypePermission> ApplicationLinkUserTypePermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
