//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacon.DAL.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Prov { get; set; }
        public Nullable<long> CountryID { get; set; }
        public string CountryMobileCode { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public long RegisteredByUserID { get; set; }
        public System.DateTime RegisteredOnDateTime { get; set; }
        public long LastModifyUserID { get; set; }
        public System.DateTime LastModifyDateTime { get; set; }
        public string LastModifyIP { get; set; }
        public bool Disable { get; set; }
        public bool Deleted { get; set; }
        public string Notes { get; set; }
        public string ClientPassword { get; set; }
        public string FullName { get; set; }
        public string CardCodeOld { get; set; }
        public string Username { get; set; }
        public Nullable<int> CardCode { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
