//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacon.StoreD.DAL.Database.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DamaconEntities : DbContext
    {
        public DamaconEntities()
            : base("name=DamaconEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationLink> ApplicationLinks { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DBBackupDetail> DBBackupDetails { get; set; }
        public virtual DbSet<DefaultLoginPage> DefaultLoginPages { get; set; }
        public virtual DbSet<Documentation> Documentations { get; set; }
        public virtual DbSet<DocumentationType> DocumentationTypes { get; set; }
        public virtual DbSet<EmailServiceItem> EmailServiceItems { get; set; }
        public virtual DbSet<EmailTaskResultItem> EmailTaskResultItems { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<LanguageMeta> LanguageMetas { get; set; }
        public virtual DbSet<LanguageResource> LanguageResources { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<WebConfiguration> WebConfigurations { get; set; }
        public virtual DbSet<ApplicationLinkUserTypePermission> ApplicationLinkUserTypePermissions { get; set; }
    }
}
