//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacon.DAL.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBBackupDetail
    {
        public long ID { get; set; }
        public string FileName { get; set; }
        public long UserID { get; set; }
        public System.DateTime BackupTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
