//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacon.DAL.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentationType()
        {
            this.Documentations = new HashSet<Documentation>();
        }
    
        public long ID { get; set; }
        public string TypeText { get; set; }
        public string Notes { get; set; }
        public long LastModifyUserID { get; set; }
        public System.DateTime LastModifyDateTime { get; set; }
        public string LastModifyIP { get; set; }
        public bool Disable { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentation> Documentations { get; set; }
        public virtual User User { get; set; }
    }
}
