//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacon.DAL.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTaskResultItem
    {
        public long ID { get; set; }
        public int SendCondition { get; set; }
        public string SentResult { get; set; }
        public System.DateTime SentDateTime { get; set; }
        public string SenderEmail { get; set; }
        public string RecipientEmail { get; set; }
    }
}
