//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacon.DAL.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailServiceItem
    {
        public long ID { get; set; }
        public int SendCondition { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPUser { get; set; }
        public string SMTPPassword { get; set; }
        public int SMTPPort { get; set; }
        public bool IsSSL { get; set; }
        public string SenderEmail { get; set; }
        public string RecipientEmail { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Notes { get; set; }
        public string LastSentResult { get; set; }
        public Nullable<System.DateTime> LastSentTime { get; set; }
        public long LastModifyUserID { get; set; }
        public System.DateTime LastModifyDateTime { get; set; }
        public string LastModifyIP { get; set; }
        public bool Disable { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> DataDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
