//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacon.DAL.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public long ID { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public long LastModifyUserID { get; set; }
        public System.DateTime LastModifyDateTime { get; set; }
        public string LastModifyIP { get; set; }
        public bool Disable { get; set; }
        public bool Deleted { get; set; }
        public string Notes { get; set; }
    }
}
