//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacon.DAL.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public long ID { get; set; }
        public string LeaveTypeTextEN { get; set; }
        public string LeaveTypeTextIT { get; set; }
    }
}
