//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacon.DAL.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Clients = new HashSet<Client>();
            this.Clients1 = new HashSet<Client>();
            this.DBBackupDetails = new HashSet<DBBackupDetail>();
            this.Documentations = new HashSet<Documentation>();
            this.DocumentationTypes = new HashSet<DocumentationType>();
            this.EmailServiceItems = new HashSet<EmailServiceItem>();
        }
    
        public long ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public long UserTypeID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Prov { get; set; }
        public Nullable<long> CountryID { get; set; }
        public string Email { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<System.DateTime> LastAccessTime { get; set; }
        public string LastAccessIP { get; set; }
        public int DefaultLoginPage { get; set; }
        public string Notes { get; set; }
        public string PitcurePath { get; set; }
        public long LastModifyUserID { get; set; }
        public System.DateTime LastModifyDateTime { get; set; }
        public string LastModifyIP { get; set; }
        public bool Disable { get; set; }
        public bool Deleted { get; set; }
        public Nullable<decimal> MonHours { get; set; }
        public Nullable<decimal> TueHours { get; set; }
        public Nullable<decimal> WedHours { get; set; }
        public Nullable<decimal> ThuHours { get; set; }
        public Nullable<decimal> FriHours { get; set; }
        public Nullable<decimal> SatHours { get; set; }
        public Nullable<decimal> SunHours { get; set; }
        public Nullable<decimal> WeeklyHours { get; set; }
    
        public virtual ApplicationLink ApplicationLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients1 { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBBackupDetail> DBBackupDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentation> Documentations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentationType> DocumentationTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailServiceItem> EmailServiceItems { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
